name: Build and Deploy to Azure ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry (ACR)
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build and Tag Docker Image
      run: |
        docker build -t detection-anomalies .   
        docker tag detection-anomalies hackathonynovgp2.azurecr.io/detection-anomalies:latest
    - name: Push Docker Image to ACR
      run: |
        docker push hackathonynovgp2.azurecr.io/detection-anomalies:latest   

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if ACI Instance Exists
      id: check-aci
      run: |
        az container show --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.ACI_CONTAINER_NAME }} >/dev/null 2>&1 || echo "notfound" > aci_status.txt

    - name: Deploy or Update Azure Container Instance (ACI)
      run: |
        if [ -f aci_status.txt ]; then
          echo "Container does not exist. Creating new instance..."
          az container create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_CONTAINER_NAME }} \
            --image hackathonynovgp2.azurecr.io/detection-anomalies:latest \
            --cpu 4 \
            --memory 7 \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --dns-name-label detection-anomalies \
            --ports 80 \
            --os-type Linux
        else
          echo "Container exists. Updating..."
          az container delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.ACI_CONTAINER_NAME }} --yes
          az container create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.ACI_CONTAINER_NAME }} \
            --image hackathonynovgp2.azurecr.io/detection-anomalies:latest \
            --cpu 4 \
            --memory 7 \
            --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.AZURE_ACR_PASSWORD }} \
            --dns-name-label detection-anomalies \
            --ports 80 \
            --os-type Linux
        fi
